### ISSUE TITLE
Replace RADx metadata template in CEDAR

### ISSUE THREAD

**Issue by marcosmro** [bmir-radx/radx-project#13]
@matthewhorridge: Reviewer
@muakdogan: Primary
@egyedia: Secondary

This is the template for the metadata files that the DCC submit. CEDAR link [here](https://auth.metadatacenter.org/auth/realms/CEDAR/protocol/openid-connect/auth?client_id=cedar-angular-app&redirect_uri=https%3A%2F%2Fcedar.metadatacenter.org%2Ftemplates%2Fedit%2Fhttps%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10%3FfolderId%3Dhttps%3A%252F%252Frepo.metadatacenter.org%252Ffolders%252F5ac6dcb6-7a9b-4a75-a945-60ae43750953&state=bf54acd8-228d-463a-84c6-269ee2039371&response_mode=fragment&response_type=code&scope=openid&nonce=152a3c48-1c9e-42ad-b349-0f6ebf35085a).

**Comment by marcosmro** [comment]
@matthewhorridge to enter some details for this task

**Comment by matthewhorridge** [comment]
We have two things that we would like to fix:

1) We would like to make a training space in one of the field names disappear (breaking)
2) We would like to weaken some list size constraints from min 1 to min 0 (backwards compatible)

My understanding is that we may have one or two instances.

The existing template is [here](
https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F5ac6dcb6-7a9b-4a75-a945-60ae43750953).

The new template is [here](https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/7262bdfd-4e46-460f-84ad-70559fdeae97?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc742ae56-1dc0-416f-b131-772ab3c9c4de)

**Comment by egyedia** [comment]
We looked into this with @muakdogan . The above is the script that we executed:

**Old template:**
	https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F5ac6dcb6-7a9b-4a75-a945-60ae43750953

```
https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10
https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10
```

**New template:**
	https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/7262bdfd-4e46-460f-84ad-70559fdeae97?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc742ae56-1dc0-416f-b131-772ab3c9c4de

```
https://repo.metadatacenter.org/templates/7262bdfd-4e46-460f-84ad-70559fdeae97
https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2F7262bdfd-4e46-460f-84ad-70559fdeae97
```

### Read the old and new template
```
curl "https://resource.metadatacenter.org/templates/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10" \
-X GET -k \
-H "Authorization: apiKey <API_KEY>" > old.json

```

```
curl "https://resource.metadatacenter.org/templates/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2F7262bdfd-4e46-460f-84ad-70559fdeae97" \
-X GET -k \
-H "Authorization: apiKey <API_KEY>" > new.json
```

### Format them, sort by key them to make the diff easy to read

```
jq '.' old.json > old-formatted.json
jq '.' new.json > new-formatted.json
diff old-formatted.json new-formatted.json

```

```
jq -S '.' old.json > old-formatted-sorted.json
jq -S '.' new.json > new-formatted-sorted.json
diff old-formatted-sorted.json new-formatted-sorted.json

```

### Check the number of instances for both

```
curl "https://resource.metadatacenter.org/search?is_based_on=https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10" \
-X GET -k \
-H "Authorization: apiKey <API_KEY>"
```
**=> total Count: 4**

```
curl "https://resource.metadatacenter.org/search?is_based_on=https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2F7262bdfd-4e46-460f-84ad-70559fdeae97" \
-X GET -k \
-H "Authorization: apiKey <API_KEY>"
```

**=> total Count: 0**

**Comment by egyedia** [comment]
The diff has these and similar looking and similar meaning blocks that look good:
**Removing the trailing spaces**
```
14468c14468
<                     "Geopolitical region ": {
---
>                     "Geopolitical region": {
```

**Changing minItems**
```
15036c15036
<       "minItems": 1,
---
>       "minItems": 0,
```

But these and similar changes are questionable:
**Going from published to draft. Could be ok, but I would like to be sure.**
```
15192c15192
<             "bibo:status": "bibo:published",
---
>             "bibo:status": "bibo:draft",
```

**Replacing a valid CEDAR field id with a UUID. Could be ok if this is used outside of CEDAR. For internal fields and elements could work even in CEDAR. But not sure if we want to do this.**
```
15274c15274
<             "@id": "https://repo.metadatacenter.org/template-fields/44367e03-8775-458e-9bf9-953ae0ad3689",
---
>             "@id": "urn:uuid:93d7bbea-36de-42c1-b977-c57072c19b15",
```

**Replacing a valid CEDAR id with an `example.com` one. Could work. Not sure if this is intentional**
```
17265c17265
<         "@id": "https://repo.metadatacenter.org/template-elements/5d2b7dcc-1926-41da-96b1-f9732f3712bc",
---
>         "@id": "http://example.org/9e2aadad-e373-4234-859d-0019c3aef15d",
```

Please confirm that these and all the similar changes are valid, and we should proceed with the replacement.

**Comment by egyedia** [comment]
This is the full diff of the formatted templates
[template-sorted-diff.txt](https://github.com/bmir-radx/radx-project/files/12770714/template-sorted-diff.txt)

**Comment by matthewhorridge** [comment]
I've regenerated the template but I'm actually now wondering whether we should do a 2.0 release... hmm..  nervous about the breaking change in the property name

**Comment by matthewhorridge** [comment]
Just to check... if field Ids and element Ids in a template change then this wouldn't affect instances right @egyedia?

**Comment by martinjoconnor** [comment]
Will have no effect.

**Comment by matthewhorridge** [comment]
Thanks @martinjoconnor

**Comment by matthewhorridge** [comment]
@egyedia here is a newer template to try.  If you could generate the same report that would be great.

https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/a5fcb9ec-b988-42b9-ab82-6cc1d56a39b0?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc742ae56-1dc0-416f-b131-772ab3c9c4de

**Comment by martinjoconnor** [comment]
One (large) task that you (and Josef and John) have discussed in the past is to manage instance evolution/compatibility/migration when templates change.

**Comment by matthewhorridge** [comment]
Yes, definitely need to talk more about this

**Comment by matthewhorridge** [comment]
In this case, I'd like to be able to do something like say, please migrate instances from Template T1 to Template T2 where possible.  If none had used "Geopolitical Region " then these instances could be migrated.  

I'd also like to revisit the decision about whether instances should be so locked down because this makes template evolution difficult.  I'm thinking of the case were we have something like `T1` with fields `{F1(required), ...}` migrating to `T2` with fields `{F1(required), ..., F2(optional)}`.  I believe that this should be non-breaking but at the moment it is a breaking change.

And, while thinking about it, consider aliases for field names.  So, "Geopolitical Region" with an alias of "Geopolitical Region "

**Comment by martinjoconnor** [comment]
Yup. I would create a task for this with a list of requirements. It's a solid amount of work, but should help RADx (and HuBMAP and CEDAR users in general).

**Comment by matthewhorridge** [comment]
What's the best repo for these issues?

**Comment by martinjoconnor** [comment]
When in doubt (and for big cross-repo issues): cedar-project

**Comment by muakdogan** [comment]
@matthewhorridge Diff with the updated version of template has some trailing space, minItems and the following difference:

```
14966c14966
<               "defaultValue": "",
---
>               "defaultValue": "http://purl.bioontology.org/ontology/MESH"
```

**Comment by matthewhorridge** [comment]
Okay, I think this looks good

**Comment by egyedia** [comment]
We had a session with @muakdogan , and we replaced the template.
In the process, we switched back from published to draft as well. Since this is not an operation supported through our API calls, we needed to do some extra steps.
I am documenting these here, somebody might need them later:

Copy the correct template to the server:
```
scp new-formatted.json user@auth.metadatacenter.org:.
```

Create a shell script to replace the document in Mongo:
```
vi update_mongo_template.sh
```

The content is:
```
#!/bin/bash
jsonContent=$(cat new-formatted.json)
mongo cedar --username USERNAME_HERE --password PASSWORD_HERE <<EOF
use cedar;
db.templates.replaceOne({ '@id': 'https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10' }, $jsonContent);
EOF
```
Make it runnable:
```
chmod a+x update_mongo_template.sh
```

Run the script, then delete it:
```
./update_mongo_template.sh
rm ./update_mongo_template.sh
```

On your local machine, tunnel neo4j:
```
ssh user@auth.metadatacenter.org -L 7474:localhost:7474 -L 7687:localhost:7687 -N
```
Open the web interface, then authenticate:
http://localhost:7474/

Update the document in Neo4j to have all the correct settings for a draft, first-of-its-kind document:
```
match (n {_id:'https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10'})
return n

match (n {_id:'https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10'})
set n.bibo_status='bibo:draft'

match (n {_id:'https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10'})
set n.pav_version='0.0.1'

match (n {_id:'https://repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10'})
set n.isLatestDraftVersion=true, n.isLatestPublishedVersion=false, n.isLatestVersion=true
```

This way the template data in Mongo and in Neo4j are in sync.
If you need to publish it, this can be done from the UI.

Lessons learned:
* we should make the search respond to UUIDs, and/or artifact ids
* the UI Info panel does not show the number of instances, or the list of their IDs, although this was a functionality present before
* Although the full path info is retrieved, the path in the Info panel is not clickable

Please validate that the template and the instances are working properly, we did check it, but yours should be the final say.

**Comment by muakdogan** [comment]
Done
